/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.UserPackage;

import Backend.ChatPackage.Message;
import Backend.UserPackage.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author Abdelrahman
 */
public class ChattingWithFriends extends javax.swing.JFrame {
    
    private User friend;
    private User currentUser;
    /**
     * Creates new form ChattingWithFriends
     */
    public ChattingWithFriends(User currentUser,User friend) {
        initComponents();
        this.friend = friend;
        this.currentUser = currentUser;
        setTitle("Chat With " + friend.getUsername() + "!");
        setLocationRelativeTo(null);
        pack();
        initCustomComponents();
    }
    
    private void initCustomComponents(){
        
        
        DefaultListModel<String> friendMessagesModel = new DefaultListModel<>();
        
                /* setting up jlists */
        chatsList.setModel(friendMessagesModel);
        
                   /* filling out data */
        for(Message message:currentUser.getUserSentMessages()){
           if(message.getMessageFriendId().equals(friend.getUserId())) friendMessagesModel.addElement(message.getMessageSenderId()+ ":" + " " + message.getMessageContent());
        }          
                          
        for(Message message:currentUser.getUserReceivedMessages()){
           if(message.getMessageSenderId().equals(friend.getUserId())) friendMessagesModel.addElement(message.getMessageSenderId()+ ":" + " " + message.getMessageContent());
        }
        
        sendMessage.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               
                createMessage messageFrame = new createMessage(currentUser,friend);
                messageFrame.setVisible(true);
     
            } 
        });
         
        
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatsList = new javax.swing.JList<>();
        sendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        chatsList.setBackground(new java.awt.Color(255, 255, 255));
        chatsList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chatsList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(chatsList);

        jTabbedPane1.addTab("Chats", jScrollPane1);

        sendMessage.setBackground(new java.awt.Color(153, 204, 255));
        sendMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendMessage.setForeground(new java.awt.Color(0, 0, 0));
        sendMessage.setText("Send Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> chatsList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton sendMessage;
    // End of variables declaration//GEN-END:variables
}
