/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.GroupPackage;

import Backend.GroupPackage.Group;
import Backend.GroupPackage.GroupDatabase;
import Backend.UserPackage.User;
import Backend.UserPackage.UserSignupSingleton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author Abdelrahman
 */
public class UserJoinedGroups extends javax.swing.JFrame {
     
    private User currentUser;
    /**
     * Creates new form UserJoinedGroups
     */
    public UserJoinedGroups() {
        initComponents();
        setTitle("UserJoinedGroups");
        setLocationRelativeTo(null);
        pack();
        this.currentUser = UserSignupSingleton.getInstance().getUser();
        initCustomComponents();
    }
    
    private void initCustomComponents(){
        
        DefaultListModel<String> userJoinedGroupsModel = new DefaultListModel<>();
        userJoinedGroupsList.setModel(userJoinedGroupsModel);
        for(Group group:currentUser.getUserJoinedGroups()){
            userJoinedGroupsModel.addElement(group.getGroupId() + " " + group.getGroupName()+ " " + group.getGroupDescription());
        }
        
        manageGroup.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                 String userId = currentUser.getUserId();
                 String line = userJoinedGroupsList.getSelectedValue();
                 String [] data = line.split(" ");
                 Group group = GroupDatabase.getInstance().getGroupById(data[0]);
                 if(group.getGroupPrimaryAdminId().equals(userId)){
                     PrimaryAdminUI primaryAdmin = new PrimaryAdminUI(group);
                     primaryAdmin.setVisible(true);
                 }
                 else if(group.getGroupOtherAdminsIds().contains(userId)){
                     OtherAdminUI otherAdmin = new OtherAdminUI(group);
                     otherAdmin.setVisible(true);
                 }
                 else if(group.getGroupMemberIds().contains(userId)){
                     NormalUserUI normalUser = new NormalUserUI(group);
                     normalUser.setVisible(true);
                 } 
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userJoinedGroupsList = new javax.swing.JList<>();
        manageGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userJoinedGroupsList.setBackground(new java.awt.Color(220, 214, 247));
        userJoinedGroupsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userJoinedGroupsList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userJoinedGroupsList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(userJoinedGroupsList);

        manageGroup.setBackground(new java.awt.Color(92, 107, 192));
        manageGroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageGroup.setForeground(new java.awt.Color(255, 255, 255));
        manageGroup.setText("Manage Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(manageGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageGroup;
    private javax.swing.JList<String> userJoinedGroupsList;
    // End of variables declaration//GEN-END:variables
}
