/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend.ContentPackage;

import Backend.ContentPackage.Post;
import Backend.ContentPackage.Story;
import Backend.UserPackage.MainUser;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author moustafa
 */
public class CreateContentP extends javax.swing.JPanel {

    private File selectedFile;

    /**
     * Creates new form ContentP
     */
    public CreateContentP() {
        initComponents();

//        this.setLayout(new FlowLayout()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        uploadPostButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        uploadStoryButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        uploadPostButton.setText("Upload Post");
        uploadPostButton.setActionCommand("");
        uploadPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPostEvent(evt);
            }
        });

        jLabel2.setText("click to add photo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        uploadStoryButton.setText("Upload Story");
        uploadStoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadStoryEvent(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uploadStoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uploadPostButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadPostButton)
                    .addComponent(uploadStoryButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            this.selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Selected file: " + this.selectedFile.getAbsolutePath());

            ImageIcon image = ImageResizer.resizeImage(this.selectedFile.getAbsolutePath(),
                    jLabel2.getWidth(), jLabel2.getHeight());

            jLabel2.setIcon(image);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void uploadPostEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPostEvent
        // TODO add your handling code here:

        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No Text Added",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Construct (builder)
        Post post = new Post(MainUser.getMainUser());

        post.setText(jTextArea1.getText());

        if (this.selectedFile != null) {
            post.setImagePath(this.selectedFile.getAbsolutePath());
        }
        //

        post.uplode();
    }//GEN-LAST:event_uploadPostEvent

    private void uploadStoryEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadStoryEvent
        // TODO add your handling code here:
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No Text Added",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Construct (builder)
        Story story = new Story(MainUser.getMainUser());

        story.setText(jTextArea1.getText());

        if (this.selectedFile != null) {
            story.setImagePath(this.selectedFile.getAbsolutePath());
        }
        //

        story.uplode();
    }//GEN-LAST:event_uploadStoryEvent


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton uploadPostButton;
    private javax.swing.JButton uploadStoryButton;
    // End of variables declaration//GEN-END:variables
}
